version: "3.8"

services:
  backend:
    build:
      context: ./Backend
      dockerfile: backend.dockerfile
    image: springbootcontactos
    depends_on:
      - db
  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=agenda2
      - MYSQL_USER=user1
      - MYSQL_PASSWORD=password
    volumes:
      - ./DB:/docker-entrypoint-initdb.d
    entrypoint: ["executable", "arg"]
