version: "3"

services:
  springboot:
    build: ./crud-jpa # Ruta al directorio que contiene el Dockerfile de Spring Boot
    restart: always
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: user1
      MYSQL_PASSWORD: password
      MYSQL_PORT: 3306
    command:
      [
        "dockerize",
        "-wait",
        "tcp://mysql:3306",
        "-timeout",
        "30s",
        "java",
        "-jar",
        "/app/target/crud-jpa-0.0.1-SNAPSHOT.jar",
      ]
    networks:
      - mi_red
    depends_on:
      - mysql

  mysql:
    container_name: mysqldb
    build: ./DB # Ruta al directorio que contiene el Dockerfile de MySQL
    restart: always
    environment:
      MYSQL_DATABASE: agenda2
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user1
      MYSQL_PASSWORD: password
    volumes:
      - ./DB/SchemaData.sql:/docker-entrypoint-initdb.d/SchemaData.sql
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - mi_red

volumes:
  mysql_data:

networks:
  mi_red:
    driver: bridge
