version: "3.8"

services:
  backend:
    build:
      context: ./Backend
      dockerfile: backend.dockerfile
    image: springbootcontactos
    depends_on:
      - db
  db:
    build:
      context: ./DB
      dockerfile: bd.dockerfile
    restart: always
    volumes:
      - ./DB:/docker-entrypoint-initdb.d
    entrypoint: ["executable", "arg"]
