FROM eclipse-temurin:17-jdk-alpine

VOLUME /tmp

RUN mkdir /app

WORKDIR /app

COPY . /app

RUN apk add --no-cache maven


RUN mvn package -DskipTests

RUN wget https://github.com/jwilder/dockerize/releases/download/v0.7.0/dockerize-alpine-linux-amd64-v0.7.0.tar.gz\
    && tar -C /usr/local/bin -xzvf dockerize-alpine-linux-amd64-v0.7.0.tar.gz \
    && rm dockerize-alpine-linux-amd64-v0.7.0.tar.gz

CMD ["java", "-jar", "/app/target/crud-jpa-0.0.1-SNAPSHOT.jar"]

EXPOSE 80