FROM eclipse-temurin:17-jdk-alpine

VOLUME /tmp

RUN mkdir /app

WORKDIR /app

COPY . /app

RUN apk add --no-cache maven


RUN mvn package -DskipTests

CMD ["java", "-jar", "/app/target/crud-jpa-0.0.1-SNAPSHOT.jar"]

EXPOSE 80